test on preliminary submission test cases

diff --git a/code/my_test b/code/my_test
--- a/code/my_test
+++ b/code/my_test
@@ -65,5 +65,19 @@ else
 fi
 
 echo "Evaluating network ${net}..."
-echo -ne "\ttest_cases/${net}/${spec}: \t"
-timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} ${verbosity} || echo "timed out (or error)"
+# echo -ne "\ttest_cases/${net}/${spec}: \t"
+# timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} ${verbosity} || echo "timed out (or error)"
+
+echo -e "\tOn \"maybe robust\" test cases (should \"maybe\" output 'verified')"
+for spec in `ls ../preliminary_submission_test_cases/${net}/maybe_robust`
+do
+	echo -ne "\t\t${spec}: \t"
+	timeout ${t}s python verifier.py --net ${net} --spec ../preliminary_submission_test_cases/${net}/maybe_robust/${spec} || echo "not verified"
+done
+
+echo -e "\tOn non-robust test cases (should output 'not verified')"
+for spec in `ls ../preliminary_submission_test_cases/${net}/not_robust`
+do
+	echo -ne "\t\t${spec}: \t"
+	timeout ${t}s python verifier.py --net ${net} --spec ../preliminary_submission_test_cases/${net}/not_robust/${spec} || echo "not verified"
+done
