implement make_dot_znet, loss and concrete

diff --git a/code/my_test b/code/my_test
--- a/code/my_test
+++ b/code/my_test
@@ -20,4 +20,4 @@ t=3
 
 echo "Evaluating network ${net}..."
 echo -ne "\ttest_cases/${net}/${spec}: \t"
-timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} || echo "timed out (or error)"
+timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} ${verbosity} || echo "timed out (or error)"
